spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    username: ${username}
    password: ${password}

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

org:
  hibernate:
    orm:
      jdbc:
        bing: trace
